### PR TITLE
switch to molecule for testing

### PR DESCRIPTION
**Pull request by ltalirz**

### CODE REVIEW

**Comment by ltalirz** [comment]
@adegomme The travis build [currently fails](https://travis-ci.org/marvel-nccr/ansible-role-bigdft/builds/492851915?utm_source=github_status&utm_medium=notification)

I suggest you still merge this PR and then make a new one to fix the issue(s).

**Comment by adegomme** [comment]
The problem is that bigdft refuses to be built by the "root" user. For the full image everything is done by the "max" user, so it does work, but molecule uses root by default, and the docker image only has an "ubuntu" user. 
So I'm not sure how to deal with this properly to have a playbook that works in both situations. Any idea ?

**Comment by ltalirz** [comment]
Interesting - I've never seen something like this with any of the other codes (and there we are, thinking the root user can do whatever he wants ;-) ).

The problems seems that it isn't creating a necessary directory
https://travis-ci.org/marvel-nccr/ansible-role-bigdft/jobs/492851916#L759

I would suggest two things:
 * figure out why it is failing and potentially report the problem upstream (I guess it _should_ be possible to build bigdft as root)
 * in the meanwhile: the Docker image we are using [has also a user 'ubuntu'](https://github.com/marvel-nccr/ubuntu-docker-base/blob/989d3861e4bbd3b35e1ca5492b6027de44df5559/Dockerfile#L22). 
You could try adding a variable `root_user: ubuntu` [to the test playbook](https://github.com/marvel-nccr/ansible-role-bigdft/blob/5392a930a2dda374811c21ef4b4db6be131e6017/molecule/default/playbook.yml#L10)
by the way, you can run the tests also locally (needs docker): `pip install molecule; molecule test`

Edit: correction, rather try `become_user` and `become: True` like [here](https://github.com/marvel-nccr/quantum-mobile/blob/master/playbook.yml#L37)

**Comment by adegomme** [comment]
Yes, I wasn't clear, I tried locally using the docker image. The folder is not there because the previous step exits prematurely saying it doesn't want to be root. It doesn't fail properly, which is a problem by itself.
I will try tomorrow to find a good way to fix the build here, while also not breaking the quantum-mobile build, which uses another user.

**Pull request merged**
